---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/19 17:36
---

---@class Circle: BaseShape
local Circle = require('sys.core.base.shape'):extend()
Circle.__name = 'Circle'

function Circle:new(radius)
  Circle.super.new(self)
  self.radius = radius or 0

  self._draw_radius = self.radius
end

function Circle:testPoint(point)
  return self:drawPosition():distance(point) <= self:drawRadius()
end

function Circle:drawRadius()
  return self._draw_radius
end

function Circle:computeDrawScale()
  Circle.super.computeDrawScale(self)
  local scale = self._draw_scale
  self._draw_radius = self.radius * (scale.x + scale.y) * 0.5
end

function Circle:draw()
  local position = self._draw_position
  love.graphics.circle(self.draw_mode, position.x, position.y, self._draw_radius)
end

return Circle
