---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/10 19:56
---

---@class Rect: BaseObject
local Rect = require('sys.core.object.base'):extend()

function Rect:new(x, y, w, h)
  Rect.super.new(self)
  self:setPosition(x or 0, y or 0)
  self.w = w or 0
  self.h = h or 0
end

function Rect:setSize(w, h)
  self.w, self.h = w, h
end

function Rect:drawSize()
  local sx, sy = self:drawScale()
  return self.w * sx, self.h * sy
end

function Rect:testPoint(px, py)
  local function checkRange(v, s, e)
    return v >= s and v < e
  end

  local x, y = self:drawPosition()
  local w, h = self:drawSize()
  return checkRange(px, x, x + w) and checkRange(py, y, y + h)
end

function Rect:draw()
  local x, y = self:drawPosition()
  local w, h = self:drawSize()
  love.graphics.rectangle(self.draw_mode, x, y, w, h)
end

return Rect
