---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/21 23:37
---

local Circle = require('sys.core.drawable.shape.circle')
local Animation = require('sys.core.drawable.animation')
local SpriteSet = require('sys.core.drawable.sprite_set')
local Drag = require('sys.core.feature.drag')

---@class AnimationTest: BaseTest
local AnimationTest = require('sys.game.test.base'):extend()

function AnimationTest:new()
  AnimationTest.super.new(self)

  self.animation = Animation()
  self:bind(self.animation)
  self.animation:addSpriteSet(
    SpriteSet.loadFromDirectory('res/sprite_character_swordman_atequipment_avatar_skin/sg_body80100'),
    SpriteSet.loadFromDirectory('res/sprite_character_swordman_atequipment_weapon_katana/(tn)sg_katana0000a', 0),
    SpriteSet.loadFromDirectory('res/sprite_character_swordman_atequipment_weapon_katana/(tn)sg_katana0000b', 0),
    SpriteSet.loadFromDirectory('res/sprite_character_swordman_atequipment_weapon_katana/(tn)sg_katana0000x', 0)
  )
  self.animation:batchSpriteSets(function(sprite_set, index)
    sprite_set:setOrigin(250, 380)
    sprite_set:batchSprites(function(sprite, index)
      sprite.rect:setVisible(true)
    end)
  end)
  self.animation:setPosition(256, 256)
  self.animation:addFrameRange(14, 23, 15)
  self.animation:setScale(2, 2)

  self.drag = Drag(self.animation)
  self:bind(self.drag)
  self.drag:setTestFunction(function(point)
    local result = false
    self.animation:batchSpriteSets(function(sprite_set, index)
      if not result then
        result = result or sprite_set:currentSprite().rect:testPoint(point)
      end
    end)
    return result
  end)

  self.pos_indicator = Circle(2)
  self:bind(self.pos_indicator)
end

function AnimationTest:update(dt)
  AnimationTest.super.update(self, dt)
  self.pos_indicator:setPosition(self.animation.position:unpack())
  self.animation:setOrientation(self.animation.radians + dt)
end

return AnimationTest
