---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/21 23:29
---

local Color = require('sys.core.feature.color')
local DynamicText = require('sys.core.drawable.dynamic_text')
local BorderEffect = require('sys.core.effect.border')

---@class BaseTest: BaseDrawable
local BaseTest = require('sys.core.base.drawable'):extend()

function BaseTest:new()
  BaseTest.super.new(self)

  local indicator = DynamicText()
  indicator:setPosition(8, 8)
  indicator:applyEffect(BorderEffect(1))

  ---@param this DynamicText
  indicator.update = function(this, dt)
    this:setText(string.format(
      '%s,%s FPS: %s',
      love.graphics.getWidth(), love.graphics.getHeight(),
      love.timer.getFPS()
    ))
  end

  self:bind(indicator)
  love.graphics.setBackgroundColor(Color(64, 64, 64):unpack())
end

return BaseTest
