---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/21 23:39
---

local Circle = require('sys.core.drawable.circle')
local Color = require('sys.core.effect.color')
local Drag = require('sys.core.feature.drag')
local Mouse = require('sys.core.input.mouse')

---@class DragTest: BaseTest
local DragTest = require('sys.game.test.base'):extend()

function DragTest:new()
  DragTest.super.new(self)

  self.circle = Circle(64)
  self.circle:setPosition(256, 256)
  self:bind(self.circle)

  self.drag = Drag(self.circle, Drag.MODE_VERTICAL)
  self.drag:addShape(self.circle)
  self.drag.event:on(self.drag.EVENT_FINISHED, function()
    self.drag:cancel()
  end)
  self:bind(self.drag)
end

function DragTest:update(dt)
  DragTest.super.update(self, dt)

  if self.circle:testPoint(Mouse.position()) then
    self.circle:applyEffect(Color(255, 0, 0))
  else
    self.circle:clearEffect(Color)
  end
end

return DragTest
