---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/12/6 22:36
---

local Updatable = require('sys.core.base.updatable')
local Drawable = require('sys.core.base.drawable')
local BorderEffect = require('sys.core.effect.border')

---@class Indicator: DynamicText
local Indicator = require('sys.core.drawable.dynamic_text'):extend()

function Indicator:new()
  Indicator.super.new(self, love.graphics.getFont())
  self:setFreeze(false)

  self:setPosition(8, 8)
  self:applyEffect(BorderEffect(1))
end

function Indicator:update(dt)
  local graphics = string.format(
    'FPS: %s\nWindow: %s, %s',
    love.timer.getFPS(),
    love.graphics.getWidth(), love.graphics.getHeight()
  )

  local objects = string.format(
    'Total: %s, Updatable: %s, Drawable: %s',
    self.parent:countChildren(),
    self.parent:countChildren(Updatable, function(object)
      return not object.freeze
    end),
    self.parent:countChildren(Drawable, function(object)
      return object.visible
    end)
  )

  self:setText(string.format('%s\n%s', graphics, objects))
end

return Indicator
