---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/21 23:41
---

local Timer = require('sys.core.feature.timer')

---@class MiscTest: BaseTest
local MiscTest = require('sys.game.test.base'):extend()

function MiscTest:new()
  MiscTest.super.new(self)

  self.timer = Timer(function(c, fc)
    print(c, fc)
  end, 1, 10):start()

  self:bind(self.timer)
end

return MiscTest
