---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/21 23:33
---

local Rect = require('sys.core.drawable.shape.rect')
local Window = require('sys.core.drawable.widget.window')
local Button = require('sys.core.drawable.widget.button')
local Color = require('sys.core.effect.color')
local Text = require('sys.core.drawable.dynamic_text')

---@class UITest: BaseTest
---@field window Window
local UITest = require('sys.game.test.base'):extend()

function UITest:new()
  UITest.super.new(self)

  self.window = Window()
  self.window:setPosition(32, 32)
  self:bind(self.window)
  self:bind(Rect(32, 32))

  local rect_1 = Rect(360, 480)
  self.window:bind(rect_1)

  ---@type Rect
  local rect_2 = Rect(360, 32)
  self.window:bind(rect_2):applyEffect(Color(255, 255, 0, 255))
  self.window.drag:addShape(rect_2)

  ---@type DynamicText
  local text = Text()

  ---@type Button
  local button = Button(
    text:node('normal'),
    text:node('hover'),
    text:node('press'),
    text:node('disabled')
  )

  button.nodes[Button.STATUS_HOVER]:applyEffect(Color(255, 128, 0))
  button.nodes[Button.STATUS_PRESS]:applyEffect(Color(255, 0, 0))
  button.nodes[Button.STATUS_DISABLED]:applyEffect(Color(64, 64, 64))
  for _, node_text in pairs(button.nodes) do
    node_text.rect:setVisible(true)
  end
  button:setPosition(300, 8)

  button.event:on(Button.EVENT_CLICKED, function()
    print(self.window.position)
  end)

  local title = text:node('Just a window')
  title:setPosition(16, 8)
  self.window:bind(title)
  self.window:bind(button)
end

return UITest
