---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/12/12 22:36
---

local Sprite = require('sys.core.drawable.node.sprite')
local Point = require('sys.core.feature.point')

---@class Popup: BaseDrawable
---@field lt Sprite|Dummy
---@field mt Sprite|Dummy
---@field rt Sprite|Dummy
---@field l Sprite|Dummy
---@field m Sprite|Dummy
---@field r Sprite|Dummy
---@field lb Sprite|Dummy
---@field mb Sprite|Dummy
---@field rb Sprite|Dummy
---@field cursor Sprite|Dummy
local Popup = require('sys.core.base.drawable'):extend()

function Popup:new(lt, mt, rt, l, m, r, lb, mb, rb)
  Popup.super.new(self)

  self.lt = self:bind(lt)
  self.mt = self:bind(mt)
  self.rt = self:bind(rt)
  self.l = self:bind(l)
  self.m = self:bind(m)
  self.r = self:bind(r)
  self.lb = self:bind(lb)
  self.mb = self:bind(mb)
  self.rb = self:bind(rb)
end

function Popup:setSize(w, h)
  self.lt:setPosition(-self.lt:getWidth(true), -self.lt:getHeight(true))
  self.mt:setPosition(0, -self.mt:getHeight(true))
  self.mt:resize(w)
  self.rt:setPosition(w, -self.rt:getHeight(true))

  self.l:setPosition(-self.l:getWidth(true), 0)
  self.l:resize(nil, h)
  self.m:resize(w, h)
  self.r:setPosition(w, 0)
  self.r:resize(nil, h)

  self.lb:setPosition(-self.lb:getWidth(true), h)
  self.mb:setPosition(0, h)
  self.mb:resize(w)
  self.rb:setPosition(w, h)
end

return Popup
