---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/12 19:13
---

local Drag = require('sys.core.feature.drag')

---@class Window: Widget
local Window = require('sys.core.base.widget'):extend()
Window.__name = 'Window'

function Window:new()
  Window.super.new(self)
  self.drag = Drag(self)
  self:bind(self.drag)
end

return Window
