---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/12/3 18:23
---

local Timer = require('sys.core.feature.timer')

---@class Animation: Updatable
---@field model Model
local Animation = require('sys.core.base.updatable'):extend()
Animation.__name = 'Animation'

function Animation:new(model)
  Animation.super.new(self)

  self.timer = Timer(function()
    self:nextFrame()
  end, 0)
  self:bind(self.timer)

  self.model = model
  ---@type table[]
  self.frames = {}

  self.loop = true
  self.current_frame = nil
  self.index = 0
end

function Animation:setModel(model)
  self.model = model
end

function Animation:setLoop(loop)
  self.loop = loop
end

---@param meta table
function Animation:addFrame(index, rate, meta)
  local frame = meta or {}
  frame.index = index
  frame.rate = rate or 30
  table.insert(self.frames, frame)
  if not self.current_frame then
    self:reset()
  end
end

function Animation:addFrameRange(index_start, index_end, rate)
  for index = index_start, index_end do
    self:addFrame(index, rate)
  end
end

function Animation:nextFrame()
  if #self.frames == 0 then
    return
  end

  self.index = self.index + 1
  local next_frame = self.frames[self.index]
  if not next_frame then
    if self.loop then
      self:reset()
    end
    return
  end

  self.timer:setTimeout(1 / next_frame.rate)
  self.timer:reset():start()
  self.current_frame = next_frame
  self.model:setCurrentFrame(next_frame.index)
end

function Animation:reset()
  self.index = 0
  self:nextFrame()
  return self
end

return Animation
