---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/19 17:36
---

---@class Circle: BaseShape
local Circle = require('sys.core.base.shape'):extend()
Circle.__name = 'Circle'

function Circle:new(radius)
  Circle.super.new(self)
  self.radius = radius or 0
end

---@param point Point
function Circle:testPoint(point)
  return self:drawPosition():distance(point) <= self:drawRadius()
end

function Circle:drawRadius()
  local scale = self:drawScale()
  return self.radius * (scale.x + scale.y) * 0.5
end

function Circle:draw()
  local pos = self:drawPosition()
  love.graphics.circle(self.draw_mode, pos.x, pos.y, self:drawRadius())
end

return Circle
