---
--- Generated by Luanalysis
--- Created by hsojo.
--- DateTime: 2022/12/1 23:03
---

local Font = require('sys.core.effect.font')
local NodeText = require('sys.core.drawable.node.text')

---@class DynamicText: Rotatable
---@field super Rotatable
local DynamicText = require('sys.core.base.rotatable'):extend()
DynamicText.__name = 'DynamicText'

function DynamicText:new(font)
  DynamicText.super.new(self)

  ---@type Font
  self.font = nil
  self:setFont(font)

  ---@type string
  self.text = nil
end

function DynamicText.loadFromTTF(path, size)
  return DynamicText(love.graphics.newFont(path, size))
end

function DynamicText.loadFromImage(path, glyphs)
  return DynamicText(love.graphics.newImageFont(path, glyphs))
end

function DynamicText:setFont(font)
  if not font then
    return
  end

  self.font = font
  self:applyEffect(Font(font))
end

function DynamicText:setText(text)
  self.text = text
end

---@param text string
---@return NodeText
function DynamicText:node(text)
  local font = self.font or love.graphics.getFont()
  local node = NodeText(love.graphics.newText(font, text))
  return node
end

function DynamicText:draw()
  local pos = self:drawPosition()
  local scale = self:drawScale()
  love.graphics.print(self.text, pos.x, pos.y, self.radians, scale.x, scale.y, self.origin:unpack())
end

function DynamicText:release()
  DynamicText.super.release(self)
  if self.font then
    self.font:release()
  end
end

return DynamicText
