---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/10 19:56
---

local Math = require('sys.core.util.math')

---@class Rect: BaseShape
local Rect = require('sys.core.base.shape'):extend()

function Rect:new(w, h)
  Rect.super.new(self)
  self.w = w or 0
  self.h = h or 0
end

function Rect:setSize(w, h)
  self.w, self.h = w, h
end

function Rect:drawSize()
  local scale = self:drawScale()
  return self.w * scale.x, self.h * scale.y
end

---@param point Point
function Rect:testPoint(point)
  local pos = self:drawPosition()
  local w, h = self:drawSize()

  return Math.inRange(
    point.x, pos.x, pos.x + w
  ) and Math.inRange(
    point.y, pos.y, pos.y + h
  )
end

---@param rect Rect
function Rect:testRect(rect)
  local pos_1 = self:drawPosition()
  local w_1, h_1 = self:drawSize()
  local pos_2 = rect:drawPosition()
  local w_2, h_2 = rect:drawSize()

  return Math.inRange(
    pos_1.x, pos_2.x - w_1, pos_2.x + w_2
  ) and Math.inRange(
    pos_1.y, pos_2.y - h_1, pos_2.y + h_2
  )
end

function Rect:draw()
  local pos = self:drawPosition()
  local w, h = self:drawSize()
  love.graphics.rectangle(self.draw_mode, pos.x, pos.y, w, h)
end

return Rect
