---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/11 00:03
---

local Rect = require('sys.core.drawable.rect')
local Rotation = require('sys.core.feature.rotation')

---@class Sprite: BaseDrawable
local Sprite = require('sys.core.base.drawable'):extend()

function Sprite:new(file)
  Sprite.super.new(self)

  ---@type Texture|Drawable
  self.image = love.graphics.newImage(file)

  ---@type Rotation
  self.rotation = Rotation()

  ---@type Rect
  self.rect = self:bind(Rect())
  self.rect:setSize(self.image:getWidth(), self.image:getHeight())
end

function Sprite:setOrientation(radians)
  self.rotation:setOrientation(radians)
end

function Sprite:setOrigin(x, y)
  self.rotation:setOrigin(x, y)
  self.rect:setPosition(-x, -y)
end

function Sprite:draw()
  local pos = self:drawPosition()
  local scale = self:drawScale()
  love.graphics.draw(self.image, pos.x, pos.y, self.rotation.radians, scale.x, scale.y, self.rotation.origin:unpack())
end

return Sprite
