---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/16 22:23
---

local json = require('sys.3rd.json')
local Point = require('sys.core.feature.point')
local Sprite = require('sys.core.drawable.node.sprite')

---@class SpriteSet: Rotatable
---@field super Rotatable
local SpriteSet = require('sys.core.base.rotatable'):extend()
SpriteSet.__name = 'SpriteSet'

function SpriteSet:new()
  SpriteSet.super.new(self)

  ---@type Sprite[]
  self.sprites = {}
  ---@type Point[]
  self.offsets = {}
  self.offset_scale = 1

  self.current_index = nil
end

---@return SpriteSet
function SpriteSet.loadFromDirectory(dir, category)
  local info = json.decode(love.filesystem.read(dir .. '/info.json'))
  local sprite_dir = string.format('%s/image', dir)
  if category then
    sprite_dir = string.format('%s_%s', sprite_dir, category)
  end

  local sprite_set = SpriteSet()
  ---@param pos table
  for index, pos in ipairs(info) do
    sprite_set.offsets[index] = Point(pos.x, pos.y)
    sprite_set.sprites[index] = sprite_set:bind(
      Sprite.loadFromFile(string.format('%s/%d.png', sprite_dir, index - 1))
    )
  end

  sprite_set:setCurrentSprite(1)
  return sprite_set
end

---@param scale number
function SpriteSet:setOffsetScale(scale)
  self.offset_scale = scale
end

function SpriteSet:setCurrentSprite(index)
  if index and index <= #self.sprites then
    self.current_index = index
  end
end

---@return Sprite
function SpriteSet:currentSprite()
  return self.sprites[self.current_index]
end

---@param process fun(sprite:Sprite, index: number)
function SpriteSet:batchSprites(process)
  for index, sprite in ipairs(self.sprites) do
    process(sprite, index)
  end
end

function SpriteSet:setOrigin(x, y)
  SpriteSet.super.setOrigin(self, x * self.offset_scale, y * self.offset_scale)

  local offset_origin = Point()
  self:batchSprites(function(sprite, index)
    sprite:setOrigin(offset_origin:base(self.origin):offset(self.offsets[index], -self.offset_scale):unpack())
  end)
end

function SpriteSet:draw()
  self:currentSprite():drawCall()
end

return SpriteSet
