---
--- Generated by Luanalysis
--- Created by hsojo.
--- DateTime: 2022/12/1 23:03
---

local Font = require('sys.core.effect.font')
local NodeText = require('sys.core.drawable.node.text')

---@class PixelText: Rotatable
---@field super Rotatable
local PixelText = require('sys.core.base.rotatable'):extend()
PixelText.__name = 'PixelText'

function PixelText:new(font)
  PixelText.super.new(self)

  ---@type Font
  self.font = nil
  self:setFont(font)

  ---@type string
  self.text = nil
end

function PixelText.loadFromTTF(path, size)
  return PixelText(love.graphics.newFont(path, size))
end

function PixelText.loadFromImage(path, glyphs)
  return PixelText(love.graphics.newImageFont(path, glyphs))
end

function PixelText:setFont(font)
  if not font then
    return
  end

  self.font = font
  self:applyEffect(Font(font))
end

function PixelText:setText(text)
  self.text = text
end

---@param text string
---@return NodeText
function PixelText:node(text)
  local font = self.font or love.graphics.getFont()
  local text = love.graphics.newText(font, text)
  return NodeText(text)
end

function PixelText:draw()
  local pos = self:drawPosition()
  local scale = self:drawScale()
  love.graphics.print(self.text, pos.x, pos.y, self.radians, scale.x, scale.y, self.origin:unpack())
end

function PixelText:release()
  PixelText.super.release(self)
  if self.font then
    self.font:release()
  end
end

return PixelText
