---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/10 19:56
---

local Math = require('sys.core.util.math')

---@class Rect: BaseDrawable
local Rect = require('sys.core.base.drawable'):extend()

function Rect:new(w, h)
  Rect.super.new(self)
  self.w = w or 0
  self.h = h or 0
  self.draw_mode = 'line'
end

function Rect:setSize(w, h)
  self.w, self.h = w, h
end

function Rect:drawSize()
  local scale = self:drawScale()
  return self.w * scale.x, self.h * scale.y
end

---@param point Point
function Rect:testPoint(point)
  local pos = self:drawPosition()
  local w, h = self:drawSize()
  return Math.in_range(
    point.x, pos.x, pos.x + w
  ) and Math.in_range(
    point.y, pos.y, pos.y + h
  )
end

function Rect:draw()
  local pos = self:drawPosition()
  local w, h = self:drawSize()
  love.graphics.rectangle(self.draw_mode, pos.x, pos.y, w, h)
end

return Rect
