---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/11 00:03
---

---@class Sprite: Rotatable
local Sprite = require('sys.core.object.rotatable'):extend()
local Rect = require('sys.core.element.rect')

function Sprite:new(file)
  Sprite.super.new(self)
  ---@type Texture|Drawable
  self.image = love.graphics.newImage(file)

  ---@type Rect
  self.rect = self:append(Rect())
  self.rect:setVisible(false)
  self.rect:setSize(self.image:getWidth(), self.image:getHeight())
end

function Sprite:setOrigin(x, y)
  Sprite.super.setOrigin(self, x, y)
  self.rect:setPosition(-x, -y)
end

function Sprite:draw()
  local pos = self:drawPosition()
  local scale = self:drawScale()
  love.graphics.draw(self.image, pos.x, pos.y, self.r, scale.x, scale.y, self.ox, self.oy)
end

return Sprite
