---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/19 20:10
---

local Table = require('sys.core.util.table')

---@class Event: BaseObject
local Event = require('sys.core.base.object'):extend()

function Event:new()
  ---@type table<string, function[]>
  self.functions = {}
end

function Event:on(event, func)
  if not self.functions[event] then
    self.functions[event] = {}
  end
  table.insert(self.functions[event], func)
end

function Event:off(event, func)
  if func then
    local functions = self.functions[event]
    if functions then
      Table.remove(functions, func)
    end
  else
    self.functions[event] = nil
  end
end

function Event:emit(event, ...)
  local functions = self.functions[event]
  if functions then
    for _, func in pairs(functions) do
      func(...)
    end
  end
end

function Event:release()
  for event, _ in pairs(self.functions) do
    self:off(event)
  end
end

return Event
