---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/12 23:17
---

local Math = {}

function Math.inRange(v, s, e)
  return v >= s and v < e
end

return Math
