---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/10 20:19
---

local Point = require('sys.core.feature.point')

---@class BaseDrawable: Updatable
---@field super Updatable
---@field parent BaseDrawable
---@field children BaseDrawable[]
local BaseDrawable = require('sys.core.base.updatable'):extend()
BaseDrawable.__name = 'Drawable'

function BaseDrawable:new()
  BaseDrawable.super.new(self)
  self.position = Point(0, 0)
  self.scale = Point(1, 1)

  ---@type table<any, Effect>
  self.effects = {}

  self.visible = true

  self._draw_position = Point()
  self._draw_scale = Point()
end

function BaseDrawable:setPosition(x, y)
  self.position:change(x or 0, y or 0)
end

function BaseDrawable:setScale(sx, sy)
  self.scale:change(sx or 1, sy or sx)
end

---@param effect Effect
function BaseDrawable:applyEffect(effect)
  self.effects[effect:type()] = effect
  effect:setDrawProcess(function()
    self:draw()
  end)
end

function BaseDrawable:clearEffect(effect_class)
  if effect_class then
    self.effects[effect_class] = nil
  else
    self.effects = {}
  end
end

function BaseDrawable:setVisible(visible)
  self.visible = visible
end

function BaseDrawable:drawPosition()
  local draw_position = self._draw_position:base(self.position)
  if self.parent then
    return draw_position:scale(self.parent:drawScale()):offset(self.parent:drawPosition())
  end
  return draw_position
end

function BaseDrawable:drawScale()
  local draw_scale = self._draw_scale:base(self.scale)
  if self.parent then
    return draw_scale:scale(self.parent:drawScale())
  end
  return draw_scale
end

function BaseDrawable:draw()
  self:drawChildren()
end

function BaseDrawable:drawChildren()
  for _, child in pairs(self.children) do
    if child:is(BaseDrawable) then
      child:drawCall()
    end
  end
end

function BaseDrawable:drawCall()
  if not self.visible then
    return
  end

  for _, effect in pairs(self.effects) do
    effect:drawBefore()
  end
  self:draw()
  for _, effect in pairs(self.effects) do
    effect:drawAfter()
  end
end

return BaseDrawable
