---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/19 14:46
---

---@class Effect: Updatable
---@field super Updatable
local Effect = require('sys.core.base.updatable'):extend()
Effect.__name = 'Effect'

function Effect:new()
  ---@type function
  self.draw_process = nil
end

---@param process function
function Effect:setDrawProcess(process)
  self.draw_process = process
end

function Effect:drawBefore()

end

function Effect:drawAfter()

end

function Effect:drawAlone()
  self:drawBefore()
  self.draw_process()
  self:drawAfter()
end

return Effect
