---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/19 14:46
---

---@class Effect: BaseObject
local Effect = require('sys.core.base.object'):extend()
Effect.__name = 'Effect'

function Effect:new()

end

function Effect:drawBefore()

end

function Effect:drawAfter()

end

return Effect
