---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/19 14:46
---

---@class BaseEffect: BaseObject
local BaseEffect = require('sys.core.base.object'):extend()
BaseEffect.__name = 'Effect'

function BaseEffect:new()

end

function BaseEffect:drawBefore()

end

function BaseEffect:drawAfter()

end

return BaseEffect
