---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/30 22:01
---

local Table = require('sys.core.feature.table')

---@class Nestable: BaseObject
local Nestable = require('sys.core.base.object'):extend()
Nestable.__name = 'Nestable'

function Nestable:new()
  ---@type Nestable
  self.parent = nil
  ---@type Nestable[]
  self.children = {}
end

---@param child Nestable
---@return Nestable, number
function Nestable:bind(child)
  local index
  local parent = child.parent
  if parent ~= self then
    if parent ~= nil then
      Table.remove(parent.children, child)
    end

    index = table.insert(self.children, child)
    child.parent = self
  end

  return child, index
end

function Nestable:release()
  for _, child in pairs(self.children) do
    child:release()
  end
  self.parent = nil
end

return Nestable
