---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/30 22:01
---

local Table = require('sys.core.feature.table')

---@class Nestable: BaseObject
local Nestable = require('sys.core.base.object'):extend()
Nestable.__name = 'Nestable'

function Nestable:new()
  ---@type Nestable
  self.parent = nil
  ---@type Nestable[]
  self.children = {}
end

---@param child Nestable
---@return Nestable, number
function Nestable:bind(child)
  ---@type number
  local index
  local parent = child.parent
  if parent ~= self then
    if parent ~= nil then
      Table.remove(parent.children, child)
    end

    index = table.insert(self.children, child)
    child.parent = self
  end

  return child, index
end

---@param process fun(child:any, index: number)
function Nestable:batchChildren(process, type)
  for index, child in pairs(self.children) do
    if not type or child:is(type) then
      process(child, index)
    end
  end
end

---@param condition fun(object: any)
function Nestable:countChildren(type, condition)
  local count = 0
  ---@param child Nestable
  self:batchChildren(function(child, index)
    if not type or child:is(type) then
      if not condition or condition(child) then
        count = count + 1
        if child:is(Nestable) then
          count = count + child:countChildren(type, condition)
        end
      end
    end
  end)
  return count
end

function Nestable:release()
  self:batchChildren(function(child, index)
    child:release()
  end)
  self.parent = nil
end

return Nestable
