---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/30 22:01
---

local Table = require('sys.core.util.table')

---@class BaseNestable: BaseObject
local BaseNestable = require('sys.core.base.object'):extend()

function BaseNestable:new()
  self.parent = nil
  ---@type BaseNestable[]
  self.children = {}
end

---@param child BaseNestable
function BaseNestable:bind(child)
  local index
  local parent = child.parent
  if parent ~= self then
    if parent ~= nil then
      Table.remove(parent.children, child)
    end

    index = table.insert(self.children, child)
    child.parent = self
  end

  return child, index
end

function BaseNestable:release()
  for _, child in pairs(self.children) do
    child:release()
  end
  self.parent = nil
end

return BaseNestable
