---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/11 00:03
---

local Rect = require('sys.core.drawable.shape.rect')

---@class Node: Rotatable
---@field super Rotatable
local Node = require('sys.core.base.rotatable'):extend()
Node.__name = 'Node'

function Node:new()
  Node.super.new(self)

  ---@type Rect
  self.rect = Rect()
  self:bind(self.rect)

  ---@type Drawable
  self.drawable = nil
end

function Node:setOrigin(x, y)
  Node.super.setOrigin(self, x, y)
  self.rect:setPosition(-x, -y)
end

---@param drawable Drawable
function Node:setDrawable(drawable)
  if not drawable then
    return
  end

  self.drawable = drawable
  self.rect:setSize(drawable:getWidth(), drawable:getHeight())
end

function Node:draw()
  local pos = self:drawPosition()
  local scale = self:drawScale()
  love.graphics.draw(self.drawable, pos.x, pos.y, self.radians, scale.x, scale.y, self.origin:unpack())
end

function Node:release()
  Node.super.release(self)
  if self.drawable then
    self.drawable:release()
  end
end

return Node
