---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/19 15:19
---

--region Classic Dummy

---@class ClassicObject
---@field super ClassicObject
local ClassicObject = {}

function ClassicObject:new()
end

function ClassicObject:extend()
end

function ClassicObject:implement(...)
end

function ClassicObject:is(T)
end

function ClassicObject:__tostring()
end

---@return ClassicObject
function ClassicObject:__call(...)
end
--endregion

local Table = require('sys.core.util.table')

---@class BaseObject: ClassicObject
local BaseObject = require('sys.3rd.classic'):extend()
BaseObject.__name = 'Object'

function BaseObject:getClass()
  return self.__index
end

function BaseObject:release()
end

function BaseObject:__tostring()
  return Table.format(self)
end

return BaseObject
