---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/11 01:01
---

local Point = require('sys.core.feature.point')

---@class Rotatable: BaseDrawable
---@field super BaseDrawable
local Rotatable = require('sys.core.base.drawable'):extend()
Rotatable.__name = 'Rotatable'

function Rotatable:new()
  Rotatable.super.new(self)
  self.radians = 0
  self.origin = Point(0, 0)
end

function Rotatable:setOrientation(radians)
  self.radians = radians
end

function Rotatable:setOrigin(x, y)
  self.origin:change(x, y)
end

return Rotatable
