---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/19 17:44
---

---@class BaseShape: BaseDrawable
local BaseShape = require('sys.core.base.drawable'):extend()
BaseShape.__name = 'Shape'
BaseShape.DrawMode = {
  ['Fill'] = 'fill',
  ['Line'] = 'line',
}

function BaseShape:new()
  BaseShape.super.new(self)
  self.draw_mode = BaseShape.DrawMode.Line
end

function BaseShape:testPoint(point)

end

return BaseShape
