---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/22 00:03
---

---@class Updatable: Nestable
---@field super Nestable
---@field parent Updatable
---@field children Updatable[]
local Updatable = require('sys.core.base.nestable'):extend()
Updatable.__name = 'Updatable'

function Updatable:new()
  Updatable.super.new(self)
  self.speed = 1
  self.active = true
end

function Updatable:setSpeed(speed)
  self.speed = speed
end

function Updatable:setActive(active)
  self.active = active
end

function Updatable:update(dt)
  self:updateChildren(dt)
end

function Updatable:updateChildren(dt)
  for _, child in pairs(self.children) do
    if child:is(Updatable) then
      child:update(dt)
    end
  end
end

function Updatable:updateCall(dt)
  if not self.active then
    return
  end

  dt = dt * self.speed
  self:update(dt)
end

return Updatable
