---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/11 23:27
---

local Event = require('sys.core.feature.event')

---@class Widget: BaseDrawable
---@field parent Widget
---@field children Widget[]
local Widget = require('sys.core.base.drawable'):extend()
Widget.__name = 'Widget'

function Widget:new()
  Widget.super.new(self)
  self:setFreeze(false)

  self.focus = false
  self.event = Event()
end

function Widget:setFocus(focus)
  self.focus = focus
  if focus and self.parent:is(Widget) then
    self.parent:setFocus(focus)
  end
end

function Widget:release()
  Widget.super.release(self)
  self.event:release()
end

return Widget
