---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/12 19:13
---

local Drag = require('sys.core.feature.drag')

---@class BaseWindow: BaseWidget
local BaseWindow = require('sys.core.widget.base'):extend()

function BaseWindow:new()
  BaseWindow.super.new(self)
  self.drag = Drag(self)
  self:bind(self.drag)
end

return BaseWindow
