---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/19 14:46
---

---@class BlendEffect: BaseEffect
local BlendEffect = require('sys.core.effect.base'):extend()
BlendEffect.Mode = {
  ['Alpha'] = 'alpha',
  ['Add'] = 'add',
  ['Subtract'] = 'subtract',
  ['Multiply'] = 'multiply',
  ['Lighten'] = 'lighten',
  ['Darken'] = 'darken',
  ['Screen'] = 'screen',
  ['Replace'] = 'replace',
  ['None'] = 'none'
}

function BlendEffect:new(mode)
  self.mode = mode
  self.prev_mode = nil
end

function BlendEffect:drawBefore()
  self.prev_mode = love.graphics.getBlendMode()
  love.graphics.setBlendMode(self.mode)
end

function BlendEffect:drawAfter()
  love.graphics.setBlendMode(self.prev_mode)
end

return BlendEffect
