---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/19 14:46
---

---@class BlendEffect: Effect
local BlendEffect = require('sys.core.base.effect'):extend()
BlendEffect.__name = 'BlendEffect'
BlendEffect.Mode = {
  ['Alpha'] = 'alpha',
  ['Add'] = 'add',
  ['Subtract'] = 'subtract',
  ['Multiply'] = 'multiply',
  ['Lighten'] = 'lighten',
  ['Darken'] = 'darken',
  ['Screen'] = 'screen',
  ['Replace'] = 'replace',
  ['None'] = 'none'
}

BlendEffect.AlphaMode = {
  ['AlphaMultiply'] = 'alphamultiply',
  ['PreMultiplied'] = 'premultiplied'
}

function BlendEffect:new(mode, alpha_mode)
  self.mode = mode
  self.alpha_mode = alpha_mode

  self.prev_mode = nil
  self.prev_alpha_mode = nil
end

function BlendEffect:drawBefore()
  self.prev_mode, self.prev_alpha_mode = love.graphics.getBlendMode()
  love.graphics.setBlendMode(self.mode, self.alpha_mode)
end

function BlendEffect:drawAfter()
  love.graphics.setBlendMode(self.prev_mode, self.prev_alpha_mode)
end

return BlendEffect
