---
--- Generated by Luanalysis
--- Created by hsojo.
--- DateTime: 2022/12/2 23:41
---

local ColorEffect = require('sys.core.effect.color')
local Point = require('sys.core.feature.point')

---@class BorderEffect: Effect
---@field super Effect
local BorderEffect = require('sys.core.base.effect'):extend()

---@param offset number
---@param color Color
function BorderEffect:new(offset, color)
  BorderEffect.super.new(self)

  ---@type ColorEffect
  self.effect = ColorEffect(color)

  ---@type Point[]
  self.offsets = {
    Point(-offset, -offset),
    Point(offset, offset),
    Point(offset, -offset),
    Point(-offset, offset),
  }
end

function BorderEffect:drawBefore()
  self.effect:drawBefore()
  for _, offset in pairs(self.offsets) do
    love.graphics.push()
    love.graphics.translate(offset:unpack())
    self.draw_process()
    love.graphics.pop()
  end
  self.effect:drawAfter()
end

return BorderEffect
