---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/19 14:46
---

---@class ColorEffect: BaseEffect
local ColorEffect = require('sys.core.effect.base'):extend()

function ColorEffect:new(r, g, b, a)
  self.color = { r, g, b, a or 255 }
  self.prev_color = nil
end

function ColorEffect:drawBefore()
  local r, g, b, a = love.graphics.getColor()
  self.prev_color = { r, g, b, a }
  love.graphics.setColor(self.color)
end

function ColorEffect:drawAfter()
  love.graphics.setColor(self.prev_color)
end

return ColorEffect
