---
--- Generated by Luanalysis
--- Created by hsojo.
--- DateTime: 2022/12/1 22:51
---

---@class FontEffect: BaseEffect
local FontEffect = require('sys.core.base.effect'):extend()
FontEffect.__name = 'FontEffect'

function FontEffect:new(font)
  ---@type Font
  self.font = font
  ---@type Font
  self.prev_font = nil
end

function FontEffect:drawBefore()
  self.prev_font = love.graphics.getFont()
  love.graphics.setFont(self.font)
end

function FontEffect:drawAfter()
  love.graphics.setFont(self.prev_font)
end

return FontEffect
