---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/11 12:30
---

local Key = require('sys.core.input.key')

local Joystick = {
  KEY_PREFIX = 'joystick_',
}

Joystick._status = {
  last_guid = nil,
  devices = {},
  states = {},
}

---@param guid string
function Joystick.key(code, guid)
  guid = guid or Joystick._status.last_guid
  return Key.get(string.format(
    '%s_%s', Joystick.KEY_PREFIX .. guid, code
  ))
end

---@return Joystick
function Joystick.device(guid)
  guid = guid or Joystick._status.last_guid
  return Joystick._status.device[guid]
end

function Joystick.axisCount(guid)
  guid = guid or Joystick._status.last_guid
  local state = Joystick._status.states[guid]
  if not state then
    return 0
  end
  return state.axis_count
end

function Joystick.axisDirection(axis, guid)
  guid = guid or Joystick._status.last_guid
  local state = Joystick._status.states[guid]
  if not state then
    return 0
  end
  return state.axis_directions[axis]
end

function Joystick.callback_updated()
  ---@param joystick Joystick
  for guid, joystick in pairs(Joystick._status.devices) do
    local state = Joystick._status.states[guid]
    if state then
      for i = 1, state.axis_count do
        state.axis_directions[i] = joystick:getAxis(i)
      end
    end
  end
end

---@param joystick Joystick
function Joystick.callback_added(joystick)
  local guid = joystick:getGUID()
  Joystick._status.devices[guid] = joystick
  Joystick._status.states[guid] = {
    axis_count = joystick:getAxisCount(),
    axis_directions = {},
  }
end

---@param joystick Joystick
function Joystick.callback_removed(joystick)
  local guid = joystick:getGUID()
  Joystick._status.devices[guid] = nil
  Joystick._status.states[guid] = nil
end

return Joystick
