---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/11 12:30
---

local Key = require('sys.core.input.key')

---@class Mouse
local Mouse = {
  KEY_PREFIX = 'mouse_',
  KEY_L = '1',
  KEY_R = '2',
  KEY_M = '3',
}

Mouse._status = {
  x = 0,
  y = 0,
  wheel_x = 0,
  wheel_y = 0,
  is_touch = false,
}

function Mouse.position()
  local status = Mouse._status
  return status.x, status.y
end

function Mouse.wheelX()
  return Mouse._status.wheel_x
end

function Mouse.wheelY()
  return Mouse._status.wheel_y
end

function Mouse.isTouch()
  return Mouse._status.is_touch
end

function Mouse.key(code)
  return Key(Mouse.KEY_PREFIX .. code)
end

function Mouse.callback_updated()
  Mouse.wheel_dx = 0
  Mouse.wheel_dy = 0
end

function Mouse.callback_moved(x, y, is_touch)
  local status = Mouse._status
  status.x, status.y, status.is_touch = x, y, is_touch
end

function Mouse.callback_wheel_moved(x, y)
  local status = Mouse._status
  status.wheel_x, status.wheel_y = x, y
end

return Mouse
