---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/19 20:25
---

local Table = {}

function Table.index(tbl, value)
  for k, v in pairs(tbl) do
    if v == value then
      return k
    end
  end
end

function Table.remove(tbl, value)
  local index = Table.index(tbl, value)
  return table.remove(tbl, index)
end

function Table.map(tbl, func)
  local new_tbl = {}
  for k, v in pairs(tbl) do
    new_tbl[k] = func(v)
  end
  return new_tbl
end

return Table
