---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/10 17:20
---

local Key = require('sys.core.input.key')
local Mouse = require('sys.core.input.mouse')
local Keyboard = require('sys.core.input.keyboard')

local DynamicText = require('sys.core.drawable.text')
local BorderEffect = require('sys.core.effect.border')

function love.load()
  io.stdout:setvbuf("no")

  ---@type BaseTest
  test = require('sys.game.test.ui')()
  test:setScale(2)

  ---@type DynamicText
  text = DynamicText()
  text:setPosition(8, 8)
  text:applyEffect(BorderEffect(2))
  test:bind(text)
end

function love.update(dt)
  test:updateCall(dt)
  text:setText(string.format(
    '%s,%s FPS: %s',
    love.graphics.getWidth(), love.graphics.getHeight(),
    love.timer.getFPS()
  ))

  Key.callback_updated()
  Mouse.callback_updated()
end

function love.draw()
  test:drawCall()
end

function love.keypressed(key)
  Key.callback_pressed(Keyboard.KEY_PREFIX .. key)
end

function love.keyreleased(key)
  Key.callback_released(Keyboard.KEY_PREFIX .. key)
end

function love.mousepressed(x, y, button, istouch, presses)
  Key.callback_pressed(Mouse.KEY_PREFIX .. button)
  Mouse.callback_moved(x, y, istouch)
end

function love.mousereleased(x, y, button, istouch, presses)
  Key.callback_released(Mouse.KEY_PREFIX .. button)
  Mouse.callback_moved(x, y, istouch)
end

function love.mousemoved(x, y, dx, dy, istouch)
  Mouse.callback_moved(x, y, istouch)
end

function love.wheelmoved(x, y)
  Mouse.callback_wheel_moved(x, y)
end
