---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/10 17:20
---

local Key = require('sys.core.input.key')
local Mouse = require('sys.core.input.mouse')
local Keyboard = require('sys.core.input.keyboard')

function love.load()
  test = require('sys.game.test.drag')()
  io.stdout:setvbuf("no")

  test:setScale(2)
  print(test)
end

function love.update(dt)
  test:updateCall(dt)
  Key.callback_updated()
  Mouse.callback_updated()
end

function love.draw()
  test:drawCall()
  love.graphics.print(string.format(
    '%s,%s FPS: %s',
    love.graphics.getWidth(), love.graphics.getHeight(),
    love.timer.getFPS()
  ))
end

function love.keypressed(key)
  Key.callback_pressed(Keyboard.KEY_PREFIX .. key)
end

function love.keyreleased(key)
  Key.callback_released(Keyboard.KEY_PREFIX .. key)
end

function love.mousepressed(x, y, button, istouch, presses)
  Key.callback_pressed(Mouse.KEY_PREFIX .. button)
  Mouse.callback_moved(x, y, istouch)
end

function love.mousereleased(x, y, button, istouch, presses)
  Key.callback_released(Mouse.KEY_PREFIX .. button)
  Mouse.callback_moved(x, y, istouch)
end

function love.mousemoved(x, y, dx, dy, istouch)
  Mouse.callback_moved(x, y, istouch)
end

function love.wheelmoved(x, y)
  Mouse.callback_wheel_moved(x, y)
end
