---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/12/13 01:50
---

---@class Dummy: Node
local Dummy = require('sys.core.base.node'):extend()

function Dummy:new(w, h)
  Dummy.super.new(self)

  self.w, self.h = w or 0, h or 0
  self:resize()
  self.rect:setVisible(true)
end

function Dummy:getWidth(no_mod)
  if not no_mod then
    return self.rect.w
  end
  return self.w
end

function Dummy:getHeight(no_mod)
  if not no_mod then
    return self.rect.h
  end
  return self.h
end

function Dummy:resize(w, h)
  w = w or self:getWidth(true)
  h = h or self:getHeight(true)
  self.rect:setSize(w, h)
end

function Dummy:draw()
  Dummy.super.super.draw(self)
end

return Dummy
