---
--- Generated by Luanalysis
--- Created by hsojo.
--- DateTime: 2022/12/2 22:47
---

---@class NodeText: Node
---@field super Node
---@field drawable Text
local NodeText = require('sys.core.base.node'):extend()
NodeText.__name = 'NodeText'

function NodeText:new(text)
  NodeText.super.new(self)
  self:setDrawable(text)
end

return NodeText
