---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/10 20:19
---

local Point = require('sys.core.util.point')

---@class BaseObject: ClassicObject
local BaseObject = require('sys.3rd.classic'):extend()
BaseObject.CK_PREV_COLOR = 'prev_color'
BaseObject.CK_PREV_BLEND_MODE = 'prev_blend_mode'

function BaseObject:new()
  self.position = Point(0, 0)
  self.scale = Point(1, 1)
  self.color = nil
  self.blend_mode = nil
  self.parent = nil
  self.children = {}
  self.context = {}
  self.visible = true
end

---@param child BaseObject
function BaseObject:bind(child)
  local index
  local parent = child.parent
  if parent ~= self then
    if parent ~= nil then
      for i, v in ipairs(parent.children) do
        if v == child then
          table.remove(parent.children, i)
          break
        end
      end
    end

    index = table.insert(self.children, child)
    child.parent = self
  end

  return child, index
end

---@param x number
---@param y number
function BaseObject:setPosition(x, y)
  self.position = Point(x or 0, y or 0)
end

---@param sx number
---@param sy number
function BaseObject:setScale(sx, sy)
  self.scale = Point(sx or 1, sy or 1)
end

function BaseObject:setColor(color)
  self.color = color
end

function BaseObject:setVisible(visible)
  self.visible = visible
end

function BaseObject:drawPosition()
  if self.parent then
    return self.position:scale(self.parent:drawScale()):offset(self.parent:drawPosition())
  end
  return self.position
end

function BaseObject:drawScale()
  if self.parent then
    return self.scale:scale(self.parent:drawScale())
  end
  return self.scale
end

function BaseObject:draw()
  self:drawChildren()
end

function BaseObject:drawBefore()
  if self.color then
    local r, g, b, a = love.graphics.getColor()
    self.context[BaseObject.CK_PREV_COLOR] = { r, g, b, a }
    love.graphics.setColor(self.color)
  end
  if self.blend_mode then
    self.context[BaseObject.CK_PREV_BLEND_MODE] = love.graphics.getBlendMode()
    love.graphics.setBlendMode(self.blend_mode)
  end
end

function BaseObject:drawAfter()
  if self.color then
    love.graphics.setColor(self.context[BaseObject.CK_PREV_COLOR])
  end
  if self.blend_mode then
    love.graphics.setBlendMode(self.context[BaseObject.CK_PREV_BLEND_MODE])
  end
end

function BaseObject:drawChildren()
  ---@param child BaseObject
  for _, child in pairs(self.children) do
    child:drawCall()
  end
end

function BaseObject:drawCall()
  if not self.visible then
    return
  end

  self:drawBefore()
  self:draw()
  self:drawAfter()
end

function BaseObject:release()
  for _, child in pairs(self.children) do
    child:release()
  end
  self.parent = nil
  self.context = nil
end

return BaseObject
