---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hsojo.
--- DateTime: 2022/11/11 01:01
---

local Point = require('sys.core.util.point')

---@class Rotation: ClassicObject
local Rotation = require('sys.3rd.classic'):extend()

function Rotation:new()
  self.radians = 0
  ---@type Point
  self.origin = Point(0, 0)
end

function Rotation:setOrientation(radians)
  self.radians = radians
end

function Rotation:setOrigin(x, y)
  self.origin = Point(x, y)
end

return Rotation
